import {MigrationInterface, QueryRunner} from "typeorm";

export class update1665668120951 implements MigrationInterface {
    name = 'update1665668120951'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "discount_condition_product" DROP CONSTRAINT "FK_f05132301e95bdab4ba1cf29a24"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product" DROP CONSTRAINT "FK_c759f53b2e48e8cfb50638fe4e0"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_type" DROP CONSTRAINT "FK_6ef23ce0b1d9cf9b5b833e52b9d"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_type" DROP CONSTRAINT "FK_e706deb68f52ab2756119b9e704"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_tag" DROP CONSTRAINT "FK_fbb2499551ed074526f3ee36241"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_tag" DROP CONSTRAINT "FK_01486cc9dc6b36bf658685535f6"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_collection" DROP CONSTRAINT "FK_a1c4f9cfb599ad1f0db39cadd5f"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_collection" DROP CONSTRAINT "FK_a0b05dc4257abe639cb75f8eae2"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_customer_group" DROP CONSTRAINT "FK_8486ee16e69013c645d0b8716b6"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_customer_group" DROP CONSTRAINT "FK_4d5f98645a67545d8dea42e2eb8"`);
        await queryRunner.query(`ALTER TABLE "product_tax_rate" DROP CONSTRAINT "FK_2484cf14c437a04586b07e7dddb"`);
        await queryRunner.query(`ALTER TABLE "product_tax_rate" DROP CONSTRAINT "FK_1d04aebeabb6a89f87e536a124d"`);
        await queryRunner.query(`ALTER TABLE "product_type_tax_rate" DROP CONSTRAINT "FK_ece65a774192b34253abc4cd672"`);
        await queryRunner.query(`ALTER TABLE "product_type_tax_rate" DROP CONSTRAINT "FK_25a3138bb236f63d9bb6c8ff111"`);
        await queryRunner.query(`ALTER TABLE "shipping_tax_rate" DROP CONSTRAINT "FK_346e0016cf045b9980747747645"`);
        await queryRunner.query(`ALTER TABLE "shipping_tax_rate" DROP CONSTRAINT "FK_f672727ab020df6c50fb64c1a70"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8486ee16e69013c645d0b8716b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d5f98645a67545d8dea42e2eb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a1c4f9cfb599ad1f0db39cadd5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0b05dc4257abe639cb75f8eae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fbb2499551ed074526f3ee3624"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01486cc9dc6b36bf658685535f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ef23ce0b1d9cf9b5b833e52b9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e706deb68f52ab2756119b9e70"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f05132301e95bdab4ba1cf29a2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c759f53b2e48e8cfb50638fe4e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2484cf14c437a04586b07e7ddd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d04aebeabb6a89f87e536a124"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ece65a774192b34253abc4cd67"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_25a3138bb236f63d9bb6c8ff11"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_346e0016cf045b998074774764"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f672727ab020df6c50fb64c1a7"`);
        await queryRunner.query(`CREATE TABLE "quotation" ("id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "sale_persion_id" character varying, "title" character varying NOT NULL, "code" character varying NOT NULL, "date" date, "customer_id" character varying, "region_id" character varying, "heading" text, "condition" text, "payment_term" text, "delivery_lead_time" date, "warranty" text, "install_support" text, "appendix_a" text, "appendix_b" text, CONSTRAINT "PK_596c572d5858492d10d8cf5383d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_16b66c932ade64e27c2c47e252" ON "quotation" ("sale_persion_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a9d713d3bd3c54be56263cb76e" ON "quotation" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0a528462b3fc7276c5a268ffcc" ON "quotation" ("region_id") `);
        await queryRunner.query(`CREATE TABLE "quotation_line" ("id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "product_id" character varying NOT NULL, "quotation_id" character varying NOT NULL, "volume" integer NOT NULL, "unit_price" integer NOT NULL, "parent_product_id" character varying NOT NULL, CONSTRAINT "PK_f7637af6733fe8751cf15d4d88f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8c6d3fd5822e44d8279a09c16f" ON "quotation_line" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a5985aa8dbbb93f3e5b555afe" ON "quotation_line" ("quotation_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1df1c5bc2c8ba51086e44a3017" ON "quotation_line" ("parent_product_id") `);
        await queryRunner.query(`ALTER TABLE "discount_condition_product" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_type" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_type" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_type" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_tag" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_tag" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_tag" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_collection" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_collection" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_collection" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_customer_group" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_customer_group" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_customer_group" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "product_tax_rate" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "product_tax_rate" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "product_tax_rate" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "product_type_tax_rate" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "product_type_tax_rate" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "product_type_tax_rate" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "shipping_tax_rate" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "shipping_tax_rate" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "shipping_tax_rate" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_customer_group" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discount_condition_customer_group" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discount_condition_customer_group" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_collection" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_collection" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_collection" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_tag" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_tag" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_tag" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_type" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_type" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_type" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "product_tax_rate" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_tax_rate" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_tax_rate" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "product_type_tax_rate" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_type_tax_rate" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_type_tax_rate" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "shipping_tax_rate" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "shipping_tax_rate" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "shipping_tax_rate" ADD "metadata" jsonb`);
        await queryRunner.query(`CREATE INDEX "IDX_f05132301e95bdab4ba1cf29a2" ON "discount_condition_product" ("condition_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c759f53b2e48e8cfb50638fe4e" ON "discount_condition_product" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ef23ce0b1d9cf9b5b833e52b9" ON "discount_condition_product_type" ("condition_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e706deb68f52ab2756119b9e70" ON "discount_condition_product_type" ("product_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fbb2499551ed074526f3ee3624" ON "discount_condition_product_tag" ("condition_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_01486cc9dc6b36bf658685535f" ON "discount_condition_product_tag" ("product_tag_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a1c4f9cfb599ad1f0db39cadd5" ON "discount_condition_product_collection" ("condition_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a0b05dc4257abe639cb75f8eae" ON "discount_condition_product_collection" ("product_collection_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8486ee16e69013c645d0b8716b" ON "discount_condition_customer_group" ("condition_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4d5f98645a67545d8dea42e2eb" ON "discount_condition_customer_group" ("customer_group_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2484cf14c437a04586b07e7ddd" ON "product_tax_rate" ("rate_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1d04aebeabb6a89f87e536a124" ON "product_tax_rate" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ece65a774192b34253abc4cd67" ON "product_type_tax_rate" ("rate_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_25a3138bb236f63d9bb6c8ff11" ON "product_type_tax_rate" ("product_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_346e0016cf045b998074774764" ON "shipping_tax_rate" ("rate_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f672727ab020df6c50fb64c1a7" ON "shipping_tax_rate" ("shipping_option_id") `);
        await queryRunner.query(`ALTER TABLE "discount_condition_customer_group" ADD CONSTRAINT "FK_4d5f98645a67545d8dea42e2eb8" FOREIGN KEY ("customer_group_id") REFERENCES "customer_group"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_condition_customer_group" ADD CONSTRAINT "FK_8486ee16e69013c645d0b8716b6" FOREIGN KEY ("condition_id") REFERENCES "discount_condition"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_collection" ADD CONSTRAINT "FK_a0b05dc4257abe639cb75f8eae2" FOREIGN KEY ("product_collection_id") REFERENCES "product_collection"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_collection" ADD CONSTRAINT "FK_a1c4f9cfb599ad1f0db39cadd5f" FOREIGN KEY ("condition_id") REFERENCES "discount_condition"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_tag" ADD CONSTRAINT "FK_01486cc9dc6b36bf658685535f6" FOREIGN KEY ("product_tag_id") REFERENCES "product_tag"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_tag" ADD CONSTRAINT "FK_fbb2499551ed074526f3ee36241" FOREIGN KEY ("condition_id") REFERENCES "discount_condition"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_type" ADD CONSTRAINT "FK_e706deb68f52ab2756119b9e704" FOREIGN KEY ("product_type_id") REFERENCES "product_type"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_type" ADD CONSTRAINT "FK_6ef23ce0b1d9cf9b5b833e52b9d" FOREIGN KEY ("condition_id") REFERENCES "discount_condition"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product" ADD CONSTRAINT "FK_c759f53b2e48e8cfb50638fe4e0" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product" ADD CONSTRAINT "FK_f05132301e95bdab4ba1cf29a24" FOREIGN KEY ("condition_id") REFERENCES "discount_condition"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_tax_rate" ADD CONSTRAINT "FK_1d04aebeabb6a89f87e536a124d" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_tax_rate" ADD CONSTRAINT "FK_2484cf14c437a04586b07e7dddb" FOREIGN KEY ("rate_id") REFERENCES "tax_rate"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_type_tax_rate" ADD CONSTRAINT "FK_25a3138bb236f63d9bb6c8ff111" FOREIGN KEY ("product_type_id") REFERENCES "product_type"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_type_tax_rate" ADD CONSTRAINT "FK_ece65a774192b34253abc4cd672" FOREIGN KEY ("rate_id") REFERENCES "tax_rate"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipping_tax_rate" ADD CONSTRAINT "FK_f672727ab020df6c50fb64c1a70" FOREIGN KEY ("shipping_option_id") REFERENCES "shipping_option"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipping_tax_rate" ADD CONSTRAINT "FK_346e0016cf045b9980747747645" FOREIGN KEY ("rate_id") REFERENCES "tax_rate"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotation" ADD CONSTRAINT "FK_16b66c932ade64e27c2c47e2526" FOREIGN KEY ("sale_persion_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotation" ADD CONSTRAINT "FK_a9d713d3bd3c54be56263cb76e4" FOREIGN KEY ("customer_id") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotation" ADD CONSTRAINT "FK_0a528462b3fc7276c5a268ffcc5" FOREIGN KEY ("region_id") REFERENCES "region"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotation_line" ADD CONSTRAINT "FK_8c6d3fd5822e44d8279a09c16f3" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotation_line" ADD CONSTRAINT "FK_9a5985aa8dbbb93f3e5b555afed" FOREIGN KEY ("quotation_id") REFERENCES "quotation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotation_line" ADD CONSTRAINT "FK_1df1c5bc2c8ba51086e44a3017a" FOREIGN KEY ("parent_product_id") REFERENCES "quotation_line"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "quotation_line" DROP CONSTRAINT "FK_1df1c5bc2c8ba51086e44a3017a"`);
        await queryRunner.query(`ALTER TABLE "quotation_line" DROP CONSTRAINT "FK_9a5985aa8dbbb93f3e5b555afed"`);
        await queryRunner.query(`ALTER TABLE "quotation_line" DROP CONSTRAINT "FK_8c6d3fd5822e44d8279a09c16f3"`);
        await queryRunner.query(`ALTER TABLE "quotation" DROP CONSTRAINT "FK_0a528462b3fc7276c5a268ffcc5"`);
        await queryRunner.query(`ALTER TABLE "quotation" DROP CONSTRAINT "FK_a9d713d3bd3c54be56263cb76e4"`);
        await queryRunner.query(`ALTER TABLE "quotation" DROP CONSTRAINT "FK_16b66c932ade64e27c2c47e2526"`);
        await queryRunner.query(`ALTER TABLE "shipping_tax_rate" DROP CONSTRAINT "FK_346e0016cf045b9980747747645"`);
        await queryRunner.query(`ALTER TABLE "shipping_tax_rate" DROP CONSTRAINT "FK_f672727ab020df6c50fb64c1a70"`);
        await queryRunner.query(`ALTER TABLE "product_type_tax_rate" DROP CONSTRAINT "FK_ece65a774192b34253abc4cd672"`);
        await queryRunner.query(`ALTER TABLE "product_type_tax_rate" DROP CONSTRAINT "FK_25a3138bb236f63d9bb6c8ff111"`);
        await queryRunner.query(`ALTER TABLE "product_tax_rate" DROP CONSTRAINT "FK_2484cf14c437a04586b07e7dddb"`);
        await queryRunner.query(`ALTER TABLE "product_tax_rate" DROP CONSTRAINT "FK_1d04aebeabb6a89f87e536a124d"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product" DROP CONSTRAINT "FK_f05132301e95bdab4ba1cf29a24"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product" DROP CONSTRAINT "FK_c759f53b2e48e8cfb50638fe4e0"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_type" DROP CONSTRAINT "FK_6ef23ce0b1d9cf9b5b833e52b9d"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_type" DROP CONSTRAINT "FK_e706deb68f52ab2756119b9e704"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_tag" DROP CONSTRAINT "FK_fbb2499551ed074526f3ee36241"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_tag" DROP CONSTRAINT "FK_01486cc9dc6b36bf658685535f6"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_collection" DROP CONSTRAINT "FK_a1c4f9cfb599ad1f0db39cadd5f"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_collection" DROP CONSTRAINT "FK_a0b05dc4257abe639cb75f8eae2"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_customer_group" DROP CONSTRAINT "FK_8486ee16e69013c645d0b8716b6"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_customer_group" DROP CONSTRAINT "FK_4d5f98645a67545d8dea42e2eb8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f672727ab020df6c50fb64c1a7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_346e0016cf045b998074774764"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_25a3138bb236f63d9bb6c8ff11"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ece65a774192b34253abc4cd67"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d04aebeabb6a89f87e536a124"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2484cf14c437a04586b07e7ddd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d5f98645a67545d8dea42e2eb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8486ee16e69013c645d0b8716b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0b05dc4257abe639cb75f8eae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a1c4f9cfb599ad1f0db39cadd5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01486cc9dc6b36bf658685535f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fbb2499551ed074526f3ee3624"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e706deb68f52ab2756119b9e70"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ef23ce0b1d9cf9b5b833e52b9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c759f53b2e48e8cfb50638fe4e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f05132301e95bdab4ba1cf29a2"`);
        await queryRunner.query(`ALTER TABLE "shipping_tax_rate" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "shipping_tax_rate" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "shipping_tax_rate" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "product_type_tax_rate" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "product_type_tax_rate" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "product_type_tax_rate" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "product_tax_rate" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "product_tax_rate" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "product_tax_rate" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_type" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_type" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_type" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_tag" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_tag" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_tag" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_collection" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_collection" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_collection" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_customer_group" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_customer_group" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "discount_condition_customer_group" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "shipping_tax_rate" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "shipping_tax_rate" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "shipping_tax_rate" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_type_tax_rate" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "product_type_tax_rate" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_type_tax_rate" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_tax_rate" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "product_tax_rate" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_tax_rate" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discount_condition_customer_group" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "discount_condition_customer_group" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discount_condition_customer_group" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_collection" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_collection" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_collection" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_tag" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_tag" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_tag" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_type" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_type" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_type" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1df1c5bc2c8ba51086e44a3017"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a5985aa8dbbb93f3e5b555afe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c6d3fd5822e44d8279a09c16f"`);
        await queryRunner.query(`DROP TABLE "quotation_line"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a528462b3fc7276c5a268ffcc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a9d713d3bd3c54be56263cb76e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_16b66c932ade64e27c2c47e252"`);
        await queryRunner.query(`DROP TABLE "quotation"`);
        await queryRunner.query(`CREATE INDEX "IDX_f672727ab020df6c50fb64c1a7" ON "shipping_tax_rate" ("shipping_option_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_346e0016cf045b998074774764" ON "shipping_tax_rate" ("rate_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_25a3138bb236f63d9bb6c8ff11" ON "product_type_tax_rate" ("product_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ece65a774192b34253abc4cd67" ON "product_type_tax_rate" ("rate_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1d04aebeabb6a89f87e536a124" ON "product_tax_rate" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2484cf14c437a04586b07e7ddd" ON "product_tax_rate" ("rate_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c759f53b2e48e8cfb50638fe4e" ON "discount_condition_product" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f05132301e95bdab4ba1cf29a2" ON "discount_condition_product" ("condition_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e706deb68f52ab2756119b9e70" ON "discount_condition_product_type" ("product_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ef23ce0b1d9cf9b5b833e52b9" ON "discount_condition_product_type" ("condition_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_01486cc9dc6b36bf658685535f" ON "discount_condition_product_tag" ("product_tag_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fbb2499551ed074526f3ee3624" ON "discount_condition_product_tag" ("condition_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a0b05dc4257abe639cb75f8eae" ON "discount_condition_product_collection" ("product_collection_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a1c4f9cfb599ad1f0db39cadd5" ON "discount_condition_product_collection" ("condition_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4d5f98645a67545d8dea42e2eb" ON "discount_condition_customer_group" ("customer_group_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8486ee16e69013c645d0b8716b" ON "discount_condition_customer_group" ("condition_id") `);
        await queryRunner.query(`ALTER TABLE "shipping_tax_rate" ADD CONSTRAINT "FK_f672727ab020df6c50fb64c1a70" FOREIGN KEY ("shipping_option_id") REFERENCES "shipping_option"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipping_tax_rate" ADD CONSTRAINT "FK_346e0016cf045b9980747747645" FOREIGN KEY ("rate_id") REFERENCES "tax_rate"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_type_tax_rate" ADD CONSTRAINT "FK_25a3138bb236f63d9bb6c8ff111" FOREIGN KEY ("product_type_id") REFERENCES "product_type"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_type_tax_rate" ADD CONSTRAINT "FK_ece65a774192b34253abc4cd672" FOREIGN KEY ("rate_id") REFERENCES "tax_rate"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_tax_rate" ADD CONSTRAINT "FK_1d04aebeabb6a89f87e536a124d" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_tax_rate" ADD CONSTRAINT "FK_2484cf14c437a04586b07e7dddb" FOREIGN KEY ("rate_id") REFERENCES "tax_rate"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_condition_customer_group" ADD CONSTRAINT "FK_4d5f98645a67545d8dea42e2eb8" FOREIGN KEY ("customer_group_id") REFERENCES "customer_group"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_condition_customer_group" ADD CONSTRAINT "FK_8486ee16e69013c645d0b8716b6" FOREIGN KEY ("condition_id") REFERENCES "discount_condition"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_collection" ADD CONSTRAINT "FK_a0b05dc4257abe639cb75f8eae2" FOREIGN KEY ("product_collection_id") REFERENCES "product_collection"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_collection" ADD CONSTRAINT "FK_a1c4f9cfb599ad1f0db39cadd5f" FOREIGN KEY ("condition_id") REFERENCES "discount_condition"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_tag" ADD CONSTRAINT "FK_01486cc9dc6b36bf658685535f6" FOREIGN KEY ("product_tag_id") REFERENCES "product_tag"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_tag" ADD CONSTRAINT "FK_fbb2499551ed074526f3ee36241" FOREIGN KEY ("condition_id") REFERENCES "discount_condition"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_type" ADD CONSTRAINT "FK_e706deb68f52ab2756119b9e704" FOREIGN KEY ("product_type_id") REFERENCES "product_type"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product_type" ADD CONSTRAINT "FK_6ef23ce0b1d9cf9b5b833e52b9d" FOREIGN KEY ("condition_id") REFERENCES "discount_condition"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product" ADD CONSTRAINT "FK_c759f53b2e48e8cfb50638fe4e0" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_condition_product" ADD CONSTRAINT "FK_f05132301e95bdab4ba1cf29a24" FOREIGN KEY ("condition_id") REFERENCES "discount_condition"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
